// <auto-generated />
using System;
using ActionVault.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ActionVault.Service.Migrations
{
    [DbContext(typeof(ActionVaultContext))]
    partial class ActionVaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("actionvault")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActionVault.Service.Entities.DailyQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("SelectedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("VaultTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VaultTaskId", "SelectedDate")
                        .IsUnique();

                    b.ToTable("DailyQueues", "actionvault");
                });

            modelBuilder.Entity("ActionVault.Service.Entities.VaultTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int?>("RecurrenceIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("RecurrenceType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("VaultTasks", "actionvault");
                });

            modelBuilder.Entity("ActionVault.Service.Entities.DailyQueue", b =>
                {
                    b.HasOne("ActionVault.Service.Entities.VaultTask", "VaultTask")
                        .WithMany("DailyQueues")
                        .HasForeignKey("VaultTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaultTask");
                });

            modelBuilder.Entity("ActionVault.Service.Entities.VaultTask", b =>
                {
                    b.Navigation("DailyQueues");
                });
#pragma warning restore 612, 618
        }
    }
}
